### ISSUE TITLE
extension found but cannot be extracted somehow

### ISSUE THREAD

**Issue by bakmanhans** [Blauwbek/pySabRename#1]
When I manually kickof the pySabRename script on a succesfully downloaded file, I get the next error message:

```
pySabRename

Searching dir: 
/var/flexshare/shares/downloads/incoming/9e6c2deef0f7b8cc364246b394201814.rar
Searching dir:  /var/flexshare/shares/downloads/incoming/9e6c2deef0f7b8cc364246b394201814.rar/76d6896d3283687edee42de65ff20503
Searching dir:  /var/flexshare/shares/downloads/incoming/9e6c2deef0f7b8cc364246b394201814.rar/76d6896d3283687edee42de65ff20503/Usenet

+Renaming process+
Found: QoQ-sbuSLN.462.H.1.5DD.LD-BEW.p0801.20E50S.yrotS.rorroH.naciremA.mkv
Old name: /var/flexshare/shares/downloads/incoming/9e6c2deef0f7b8cc364246b394201814.rar/76d6896d3283687edee42de65ff20503/QoQ-sbuSLN.462.H.1.5DD.LD-BEW.p0801.20E50S.yrotS.rorroH.naciremA.mkv
Traceback (most recent call last):
  File "./pySabRename_unix.py", line 77, in <module>
    print 'Found extension! ({})'.format(ext)
ValueError: zero length field name in format
```

I call the script on my CentOS 6 system like this:

```
./pySabRename_unix.py /downloads/incoming/9e6c2deef0f7b8cc364246b394201814.rar 9e6c2deef0f7b8cc364246b394201814.rar.nzb 9e6c2deef0f7b8cc364246b394201814.rar 123 series alt.binaries.boneless 0
```

**Comment by Blauwbek** [comment]
Can I ask you what python version you are using? This problem appears to be a python 2.6 thing...
As far as I can find, a tempfix would be to replace line 77 with the following:
`print 'Found extension! ({0})'.format(ext)`

**Comment by bakmanhans** [comment]
`# python -V`
`Python 2.6.6`

I will try your suggestion

**Comment by bakmanhans** [comment]
Bingo! Your suggestion worked on my environment:
`+Renaming process+
Found: QoQ-sbuSLN.462.H.1.5DD.LD-BEW.p0801.20E50S.yrotS.rorroH.naciremA.mkv
Old name: /var/flexshare/shares/downloads/incoming/9e6c2deef0f7b8cc364246b394201814.rar/76d6896d3283687edee42de65ff20503/QoQ-sbuSLN.462.H.1.5DD.LD-BEW.p0801.20E50S.yrotS.rorroH.naciremA.mkv
Found extension! (.mkv)
Extention supported! .mkv`

**Comment by bakmanhans** [comment]
hold on. this doesn't look good:
`New name: /var/flexshare/shares/downloads/incoming/9e6c2deef0f7b8cc364246b394201814.rar/9e6c2deef0f7b8cc364246b394201814.rar.mkv`

**Comment by Blauwbek** [comment]
It does, though. You specified the job name as being
9e6c2deef0f7b8cc364246b394201814.rar
and pySR will simply append the extension, because it expects the
job name in sabnzbd to be set to the correct title.

**Comment by bakmanhans** [comment]
OK, makes sense. But those jobs with backup links etc. do have these random names. How does pySR cope with it?

**Comment by Blauwbek** [comment]
It doesnt, it expects the downloader (either a person or a piece of software) to handle that.

**Comment by bakmanhans** [comment]
Any specific recommendation to handle this software-matically? I hate doing it manually...

**Comment by Blauwbek** [comment]
You can set the third argument of the script to the argument if you run the script manually. It would be the best to automatically give the right title to sab (e.g. rss)
