### ISSUE TITLE
Renaming goes wrong

### ISSUE THREAD

**Issue by pven** [Blauwbek/pySabRename#3]
Hi!

When I look in the logging I see:

```
+Renaming process+
Found: 03aeb136da5674006173ddb8d57223bd.mkv
Old name: /volume1/media/Movies/The Martian (2015) x264 720p Bluray DD5_1 + DTS NLSubs -Q o Q-/db32275d8bdd3716004765ad631bea30/03aeb136da5674006173ddb8d57223bd.mkv
Found extension! (.mkv)
Extention supported! .mkv
New name: /volume1/media/Movies/The Martian (2015) x264 720p Bluray DD5_1 + DTS NLSubs -Q o Q-/The Martian (2015) x264 720p Bluray DD5_1 + DTS NLSubs -Q o Q-.mkv
```

But when I look at my disk I see:

```
The Martian (2015) 720p HQ AC3 DD5.1 (Ingebakken Subs).avi
```

Is this some kind of bug? (This is the only post-process I run.)

The content of pySR.cfg:

```
[Static]
vidext=.mkv,.avi,.mp4,.3gp,.divx,.flv,.mpg,.m4v,.mov,.mpeg,.swf,.wmv,.iso
subext=.idx,.sub,.srt
[sabnzbd]
moviecat=movies
tvcat=tv sick beard
[tv]
cleanup=yes
sickbeard=no
[movies]
```

Btw: I am using Python 2.7.9

**Comment by Blauwbek** [comment]
You would assume this should work correctly, do you use the version with par2 support?

**Comment by pven** [comment]
Thanks for the fast answer!

No, I am using pySabRename_syno.py

(It happened before, but I forgot to log a issue for it)

**Comment by Blauwbek** [comment]
Could you maybe put the whole log here or on a pm?

**Comment by pven** [comment]
I don't like Brein, so PM it is. How can I send it to you? I can't find a PM-button here.

**Comment by Blauwbek** [comment]
It appears that that is not possible anymore :-1:

**Comment by pven** [comment]
Here it is: pastebin

**Comment by Blauwbek** [comment]
Could you try to ssh into your syno and do the following:
`du "/volume1/media/Movies/The Martian (2015) x264 720p Bluray DD5_1 + DTS NLSubs -Q o Q-/The Martian (2015) x264 720p Bluray DD5_1 + DTS NLSubs -Q o Q-.mkv"`

and maybe `ls -al "/volume1/media/Movies/The Martian (2015) x264 720p Bluray DD5_1 + DTS NLSubs -Q o Q-"` while we're at it, because I'm a bit at a loss at what is happening

**Comment by pven** [comment]
Here it is:

```
DiskStation> du "/volume1/media/Movies/The Martian (2015) x264 720p Bluray DD5_1 + DTS NLSubs -Q o Q-/The Martian (2015) x264 720p Bluray DD5_1 + DTS NLSubs -Q o Q-.mkv"
7275696 /volume1/media/Movies/The Martian (2015) x264 720p Bluray DD5_1 + DTS NLSubs -Q o Q-/The Martian (2015) x264 720p Bluray DD5_1 + DTS NLSubs -Q o Q-.mkv
DiskStation> ls -al "/volume1/media/Movies/The Martian (2015) x264 720p Bluray DD5_1 + DTS NLSubs -Q o Q-"
drwxrwxrwx    2 sabnzbd  users         4096 Dec 31 15:26 .
drwxrwxrwx  149 sabnzbd  users        12288 Jan  1 21:54 ..
-rw-rw-rw-    1 sabnzbd  users         1777 Dec 31 15:21 QoQ.nfo
-rw-rw-rw-    1 sabnzbd  users    7450301205 Dec 29 21:51 The Martian (2015) x264 720p Bluray DD5_1 + DTS NLSubs -Q o Q-.mkv
DiskStation>
```

**Comment by pven** [comment]
Huh, now I am really lost. Where is the avi-file?

**Comment by pven** [comment]
Oh f_ck, d_mn! I know what is wrong ... I am ashamed!

The movie is on my disk TWICE, in different folders. I checked the wrong folder when complaining.

Sorry ...

**Comment by Blauwbek** [comment]
No problem, I had secretly hoped for such a scenario, therefore the ls command :)
Happy renaming!
