### ISSUE TITLE
Script results in error message in SABNZBD

### ISSUE THREAD

**Issue by heelergjammer** [Blauwbek/pySabRename#4]
Hi,

today I wanted to setup your script.
I did everything mentioned in the readme, but I get the following error messages shown in SABNZBD for every QOQ release I download:

Found extension! (.mkv)
processing par2 file f:\SABnzbd\BROOKLYN Nine-Nine (2015) S03E11 H.264 (WEB-DL) DD5.1 1080p NLSubs -Q o Q-\a8c8c046aefe0145ef15dde8479eb8f1\Rename.With.This.par2
Traceback (most recent call last):
  File "D:\SABNZBD_Scripts\pySabRename_win.py", line 107, in <module>
    R=subprocess.call(['par2.exe','r','-q',par_file,'_'],cwd=dir_name)
  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(_popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 710, in **init**
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] Het systeem kan het opgegeven bestand niet vinden

Further info/details:
- Windows 10 Pro
- SABNZBD 0.7.20
- Selected script: pySabRename_win.py
- Spotnet 2.00.150

Am I doing something wrong?

**Comment by Blauwbek** [comment]
@mesa98 Could you look at this?

**Comment by Blauwbek** [comment]
@mesa57 Could you look at this?

**Comment by mesa57** [comment]
For par2 execution you have to place the par2.exe in the pysabrename.exe folder too.
You can use the par2.exe found in the sabnzbd lib folder.

**Comment by mesa57** [comment]
Created a new pull request for support for par2j, check added if par2j.exe is present, added windows dist folder.

**Comment by heelergjammer** [comment]
hi, i will check this out soon. I'm out of the country right now, be back in a few days. thanks in advance

**Comment by heelergjammer** [comment]
Works like a charm now. Thanks!
